version: '3.8'

services:
  youtube-subtitle:
    build: .
    container_name: youtube-subtitle
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=8000
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
